// get part-
export const GET_PART_REQUEST = "GET_PART_REQUEST";
export const GET_PART_SUCCESS = "GET_PART_SUCCESS";
export const GET_PART_ERROR = "GET_PART_ERROR";

// get single part-
export const GET_SINGLE_PART_REQUEST = "GET_SINGLE_PART_REQUEST";
export const GET_SINGLE_PART_SUCCESS = "GET_SINGLE_PART_SUCCESS";
export const GET_SINGLE_PART_ERROR = "GET_SINGLE_PART_ERROR";

// add new part-
export const ADD_NEW_PART_REQUEST = "ADD_NEW_PART_REQUEST";
export const ADD_NEW_PART_SUCCESS = "ADD_NEW_PART_SUCCESS";
export const ADD_NEW_PART_ERROR = "ADD_NEW_PART_ERROR";

// update part-
export const UPDATE_PART_REQUEST = "UPDATE_PART_REQUEST";
export const UPDATE_PART_SUCCESS = "UPDATE_PART_SUCCESS";
export const UPDATE_PART_ERROR = "UPDATE_PART_ERROR";

// delete part-
export const DELETE_PART_REQUEST = "DELETE_PART_REQUEST";
export const DELETE_PART_SUCCESS = "DELETE_PART_SUCCESS";
export const DELETE_PART_ERROR = "DELETE_PART_ERROR";